[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200

; Configuration du système de fichiers - CRUCIAL
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

lib_deps =
  bblanchon/ArduinoJson@^6.21.4